" Environment
set undodir=$XDG_CACHE_HOME/vim/undo
set backupdir=$XDG_DATA_HOME/vim/backup//
set directory=$XDG_DATA_HOME/vim/swp//
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Setting up Vundle - the vim plugin bundler
  let InstallPlugins=0
  let vundle_readme=expand("$XDG_CONFIG_HOME/vim/bundle/Vundle.vim/README.md")
  if !filereadable(vundle_readme)
    echo "Installing Vundle.."
    echo ""
    silent !mkdir -p $XDG_CONFIG_HOME/vim/bundle
    silent !git clone https://github.com/VundleVim/Vundle.vim $XDG_CONFIG_HOME/vim/bundle/Vundle.vim
    let InstallPlugins=1
  endif

  set nocompatible
  filetype off  " Used for Vundle
  set rtp+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
  call vundle#begin('$XDG_CONFIG_HOME/vim/bundle')

  Plugin 'VundleVim/Vundle.vim'

  " Color schemes
  Plugin 'arcticicestudio/nord-vim'

  Plugin 'ctrlpvim/ctrlp.vim'
  Plugin 'fisadev/vim-ctrlp-cmdpalette'
  Plugin 'mileszs/ack.vim'
  Plugin 'w0rp/ale'
  Plugin 'vim-airline/vim-airline'
  Plugin 'vim-airline/vim-airline-themes'
  Plugin 'tpope/vim-fugitive'
  Plugin 'tpope/vim-commentary'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-rsi'
  Plugin 'christoomey/vim-tmux-navigator'
  Plugin 'wesQ3/vim-windowswap'
  Plugin 'vimwiki/vimwiki'
  Plugin 'tpope/vim-vinegar'
  Plugin 'dbakker/vim-projectroot'

  Plugin 'sheerun/vim-polyglot'
  Plugin 'python-mode/python-mode'
  Plugin 'magicalbanana/vim-sql-syntax'

  if !has('nvim')
    Plugin 'tpope/vim-sensible'
    Plugin 'tpope/vim-dispatch'
  endif

  if InstallPlugins == 1
    echo "Installing plugins"
    echo ""
    :PluginInstall
  endif
  call vundle#end()

  filetype plugin indent on
  colorscheme nord
" Setting up Vundle - the vim plugin bundler end

set encoding=utf-8
set fileencoding=utf8

" Hide buffers
set hidden

let mapleader="\<SPACE>"

" Fast tab switching via number
nnoremap <Leader>1 :1tabnext<CR>
nnoremap <Leader>2 :2tabnext<CR>
nnoremap <Leader>3 :3tabnext<CR>
nnoremap <Leader>4 :4tabnext<CR>
nnoremap <Leader>5 :5tabnext<CR>
nnoremap <Leader>6 :6tabnext<CR>
nnoremap <Leader>7 :7tabnext<CR>
nnoremap <Leader>8 :8tabnext<CR>
nnoremap <Leader>9 :9tabnext<CR>
nnoremap <Leader>0 :10tabnext<CR>

nnoremap <Leader>tn :tabnext<CR>
nnoremap <Leader>tp :tabprevious<CR>
nnoremap <Leader>tN :+tabmove<CR>
nnoremap <Leader>tP :-tabmove<CR>
nnoremap <Leader>tc :tabnew<CR>
nnoremap <Leader>tx :tabclose<CR>


" Utility keymappings
nmap <leader>l :setlocal number!<CR>
nmap <leader>o :set paste!<CR>

if has('nvim')
  " Make it easy to navigate out of the neovim terminal.
  nnoremap <a-j> <c-w>j
  nnoremap <a-k> <c-w>k
  nnoremap <a-h> <c-w>h
  nnoremap <a-l> <c-w>l
  vnoremap <a-j> <c-\><c-n><c-w>j
  vnoremap <a-k> <c-\><c-n><c-w>k
  vnoremap <a-h> <c-\><c-n><c-w>h
  vnoremap <a-l> <c-\><c-n><c-w>l
  inoremap <a-j> <c-\><c-n><c-w>j
  inoremap <a-k> <c-\><c-n><c-w>k
  inoremap <a-h> <c-\><c-n><c-w>h
  inoremap <a-l> <c-\><c-n><c-w>l
  cnoremap <a-j> <c-\><c-n><c-w>j
  cnoremap <a-k> <c-\><c-n><c-w>k
  cnoremap <a-h> <c-\><c-n><c-w>h
  cnoremap <a-l> <c-\><c-n><c-w>l
  tnoremap <a-j> <c-\><c-n><c-w>j
  tnoremap <a-k> <c-\><c-n><c-w>k
  tnoremap <a-h> <c-\><c-n><c-w>h
  tnoremap <a-l> <c-\><c-n><c-w>l
  au WinEnter term://* startinsert

  " Easy-to-open terminals.
  map <F2> :terminal<CR>
  map <leader><F2> :e term://
endif

" Slack code from vim
" Requires installation of slackecho
map <leader>sc :let g:SlackChannel=input("Slack user/channel: ")<CR>
nmap <leader>sb :exec "w !slackcat -c " . (exists("g:SlackChannel") ? g:SlackChannel : input("Slack user/channel: "))<CR>
vmap <leader>sb :<C-u>exec "'<,'>w !slackcat -c " . (exists("g:SlackChannel") ? g:SlackChannel : input("Slack user/channel: "))<CR>

" More natural split opening
set splitbelow
set splitright

" Minimized panes show only the status bar.
set winminheight=0

" Quickly resize windows with vertical split
map - <C-W>-
map + <C-W>+

" Automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" Use system clipboard
set clipboard=unnamed

" APPEARANCE

set guifont=Sauce\ Code\ Powerline:h14

" highlight current line
set cursorline

" No vertical fill character
set fillchars="vert:\ "

" SEARCHING

" Ignore case when searching
set ignorecase

" Respect case when searching with uppercase
set smartcase

" Highlight search matches
set hlsearch

" Shortcut to clear search matches
nmap <leader>q :nohlsearch<CR>

" Python mode
let g:pymode_rope = 0
let g:pymode_doc = 0
let g:pymode_folding = 0
let g:pymode_python = 'python3'

" Airline appearance
let g:airline_powerline_fonts = 1

" Don't use the ugly default separators.
let g:airline_left_sep=''
let g:airline_right_sep=''

" Let airline know when a file was modified.
" let g:airline_detect_modified = 1

let g:airline_section_z = '%{airline#util#wrap(airline#extensions#windowswap#get_status(),0)}%3p%% %4l/%L:%3v'

" Airline tabline tweaks. This prevents buffers from showing up in the
" tabline, only shows the tabline when there is more than one tab,
" and shows the tab number instead of window count.
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#tab_min_count = 2
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#buffer_idx_mode = 1

" Don't show statusline junk on inactive windows.
let g:airline_inactive_collapse=1

" Default tabs
set expandtab
set shiftwidth=2
set softtabstop=2

autocmd Filetype php setlocal sw=4 sts=4
autocmd Filetype python setlocal sw=4 sts=4
autocmd FileType mail setlocal fo+=aw fo-=t noet lbr nolist wrap spell spl=en
autocmd FileType markdown setlocal nonu tw=79
autocmd FileType text setlocal nonu noet wrap lbr nolist fo-=t spell spl=en
autocmd FileType git setlocal nofen

" Make Vim recognize *.md as Markdown, not Modula-2.
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Make vim overwrite the crontab when editing.
autocmd filetype crontab setlocal nobk nowb

" Strip trailing whitespace when saving.
autocmd FileType php,python,ruby,javascript,html,css autocmd BufWritePre * %s/\s\+$//e

nmap <Leader>wl <Plug>VimwikiUISelect
nmap <Leader>wx <Plug>VimwikiToggleListItem

let g:vimwiki_list = [{'path': '$HOME/notes/text/', 'path_html': '$HOME/notes/html/', 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_diary_months = {
      \ 1: '一月', 2: '二月', 3: '三月',
      \ 4: '四月', 5: '五月', 6: '六月',
      \ 7: '七月', 8: '八月', 9: '九月',
      \ 10: '十月', 11: '十一月', 12: '十二月'
      \ }

" Prevent windowswap from clashing with vimwiki.
let g:windowswap_map_keys = 0
nnoremap <silent> <leader>ws :call WindowSwap#EasyWindowSwap()<CR>

" Use the silver searcher if it's installed
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

let g:ack_use_dispatch = 0  " I appear to get no results with this set.

" Make ctrl-p open a file, even if it's already open.
let g:ctrlp_switch_buffer = 0

" Make ctrl-p open files in whatever my current window is.
let g:ctrlp_reuse_window = 'netrw\|help\|quickfix\|term'

" Show hidden files in ctrl-p.
let g:ctrlp_show_hidden = 1

" CtrlP ignore files
" set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.exe
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(pyo|pyc|exe|so|dll|tmp|swp|zip)$',
  \ }

nmap <leader>; :CtrlPCmdPalette<CR>

" Fast buffer switching via ctrl-p.
nnoremap <F5> :CtrlPBuffer<CR>
nnoremap <F9> :CtrlPBufTag<CR>
nnoremap <F8> :CtrlPBufTagAll<CR>
nnoremap <leader><F8> :CtrlPTag<CR>

" Project-aware find/search
map <leader>p* :exec "CtrlP " . ProjectRootGuess()<CR>
map <leader>* :exec "Ack " . expand("<cword>") . " " . ProjectRootGuess()<CR>

" fugitive shortcuts
map <leader>gs :Gstatus<CR>
map <leader>gc :Gcommit<CR>
map <leader>gm :Gmerge<CR>
map <leader>gpl :Gpull<CR>
map <leader>gps :Gpush<CR>
map <leader>gf :Gfetch<CR>
map <leader>gl :Glog<CR>
map <leader>gr :Gread<CR>
map <leader>gw :Gwrite<CR>
map <leader>gd :Gdiff<CR>
map <leader>gb :Gblame<CR>

let localrc=expand("$XDG_CONFIG_HOME/vim/localrc")
if filereadable(localrc)
  exec "source " . localrc
endif
